name: Build test
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      C_WARN: "-Wall -Wextra -Wno-error=unused-result -Wno-pointer-sign -Wno-unused-parameter -Wno-sign-compare"
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y \
            libreadline6-dev \
            autoconf \
            automake \
            python3-pytest

      - name: Prepare (autoreconf)
        run: autoreconf -i

      - name: Prepare (configure)
        env:
          CFLAGS: "-g -O2 -fsanitize=address,undefined -fno-omit-frame-pointer -Werror ${{ env.C_WARN }}"
          LDFLAGS: "-fsanitize=address,undefined"
        run: ./configure

      - name: Build
        run: make

      - name: Run pytest
        env:
          ASAN_OPTIONS: "detect_leaks=1"
          UBSAN_OPTIONS: "print_stacktrace=1"
        run: pytest -v

      - name: Run check
        run: make check
